FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt pyproject.toml alembic.ini ./
COPY backend ./backend
RUN pip install --no-cache-dir -r requirements.txt -e .

CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]