"""add application team members

Revision ID: 6c61bfe05014
Revises: f6a1b2c3d4e5
Create Date: 2026-07-05 17:25:14.346453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c61bfe05014'
down_revision: Union[str, None] = 'f6a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_member_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_team_members_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], name=op.f('fk_application_team_members_team_member_id_team_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_team_members')),
    sa.UniqueConstraint('team_member_id', 'application_id', name=op.f('uq_application_team_members_team_member_id'))
    )
    op.create_index('ix_application_team_members_application_id', 'application_team_members', ['application_id'], unique=False)
    op.create_index('ix_application_team_members_team_member_id', 'application_team_members', ['team_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_team_members_team_member_id', table_name='application_team_members')
    op.drop_index('ix_application_team_members_application_id', table_name='application_team_members')
    op.drop_table('application_team_members')
    # ### end Alembic commands ###
