"""add github identity to users

Revision ID: f94b5dd9480e
Revises: 6c61bfe05014
Create Date: 2026-07-05 17:46:49.033547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b5dd9480e'
down_revision: Union[str, None] = '6c61bfe05014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_email')
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
